export const MAIN_ROUTE = '/'
export const SIGN_IN_ROUTE = '/sign-in'
export const SIGN_UP_ROUTE = '/sign-up'
export const FORUM_ROUTE = '/forum'
export const LEADERBOARD_ROUTE = '/leaderboard'
export const PROFILE_ROUTE = '/profile'
