openapi: 3.0.0
info:
  version: 1.0.0
  title: Swagger API
  description: snake game
servers:
  - url: http://localhost:3001/api/v1/
tags:
  - name: Theme
    description: ''
  - name: LeaderBoard
    description: ''
  - name: Forum
    description: ''
paths:
  /theme/{idUser}:
    get:
      summary: Get a user's theme
      tags: [Theme]
      parameters:
        - name: idUser
          in: path
          description: User ID
          required: true
          type: string
      responses:
        200:
          description: Success
    post:
      summary: Post a user's theme
      tags: [Theme]
      parameters:
        - name: idUser
          in: path
          description: User ID
          required: true
          type: string
          example: sdf4
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              required:
                - theme
              properties:
                theme:
                  type: string
      responses:
        200:
          description: Success
    put:
      summary: Put a user's theme
      tags: [Theme]
      parameters:
        - name: idUser
          in: path
          description: User ID
          required: true
          type: string
          example: sdf4
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              required:
                - theme
              properties:
                theme:
                  type: string
      responses:
        200:
          description: Success
  /leaderboard:
    get:
      summary: массив всех пользователей (фильтр по очкам)
      tags: [LeaderBoard]
      responses:
        200:
          description: Success
  /leaderboard/{idUser}:
    get:
      summary: получение очков пользователя
      tags: [LeaderBoard]
      parameters:
        - name: idUser
          in: path
          description: User ID
          required: true
          type: integer
      responses:
        200:
          description: Success
    post:
      summary: запись очков пользователя (здесь проверка - записывается всегда наибольшее кол-во очков)
      tags: [LeaderBoard]
      parameters:
        - name: idUser
          in: path
          description: User ID
          required: true
          type: string
          example: sdf4
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              required:
                - point
              properties:
                point:
                  type: number
      responses:
        200:
          description: Success
  /forum:
    get:
      summary: список всех топиков
      tags: [Forum]
      responses:
        200:
          description: Success
    post:
      summary: создание топика
      tags: [Forum]
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              required:
                - title
                - creatorUserId
              properties:
                title:
                  type: string
                creatorUserId:
                  type: string
      responses:
        200:
          description: Success
  /forum/{topicId}/responses:
    get:
      summary: список всех ответов
      tags: [Forum]
      parameters:
        - name: topicId
          in: path
          description: User ID
          required: true
          type: number
      responses:
        200:
          description: Success
    post:
      summary: запись ответа в топик
      tags: [Forum]
      parameters:
        - name: topicId
          in: path
          description: User ID
          required: true
          type: number
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              required:
                - text
                - idUser
              properties:
                text:
                  type: string
                idUser:
                  type: string
      responses:
        200:
          description: Success
