export const MAIN_ROUTE = '/'
export const SIGN_IN_ROUTE = '/sign-in'
export const SIGN_UP_ROUTE = '/sign-up'
export const FORUM_ROUTE = '/forum'
export const LEADERBOARD_ROUTE = '/leaderboard'
export const PROFILE_ROUTE = '/profile'
export const GAME_ROUTE = '/game'
export const ERROR_ROUTE = '/error'

export const SERVER_BASE = 'https://england-snake-21.ya-praktikum.tech'
export const SERVER_PORT = ''
export const SERVER_API = '/api/v1/'
